#!/bin/bash

if test -f /usr/bin/apt-get; then
    sudo apt-get install $1
fi

if test -f /usr/bin/zypper; then
    sudo zypper install $1
fi

if test -f /usr/bin/dnf; then
    sudo dnf install $1
fi

if test -f /usr/bin/yum; then
    sudo yum install $1
fi
