#!/bin/bash

if command -v apt-get &> /dev/null
then
    sudo apt-get install $1
    exit
fi

if command -v zypper &> /dev/null
then
    sudo zypper install $1
    exit
fi

if command -v dnf &> /dev/null
then
    sudo dnf install $1
    exit
fi

if command -v yum &> /dev/null
then
    sudo yum install $1
    exit
fi

if command -v yay &> /dev/null
then
    sudo yay -S $1
    exit
fi
